name: Pull Request Check

on:
  - pull_request

jobs:
  ckeck:
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash
        working-directory: ./fluxo-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v