name: Pull Request Check

on:
  - pull_request

jobs:
  ckeck:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        # Usamos una acción estándar para configurar Python. Es más fiable.
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Activa el caché para acelerar instalaciones futuras

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v --disable-warnings --maxfail=1